In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [9]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [11]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
n = np.array([
     [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]
 ])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n[0, 1]

np.int64(2)

In [16]:
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
n[2]

array([7, 8, 9])

In [18]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [19]:
n[:, 1]

array([20,  5,  1])

In [20]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [21]:
np.random.rand(5, 2)

array([[0.13705251, 0.73452842],
       [0.4831975 , 0.78026198],
       [0.54910665, 0.75051768],
       [0.11526943, 0.91006128],
       [0.21601173, 0.7495867 ]])

In [22]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [23]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [24]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [25]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [26]:
a + 1

array([1, 2, 3, 4, 5])

In [27]:
a * 2

array([0, 2, 4, 6, 8])

In [28]:
b = (10 + (a * 2)) **2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [29]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [30]:
a >= 2

array([False, False,  True,  True,  True])

In [31]:
a > b

array([False, False,  True,  True,  True])

In [32]:
a[a > b]

array([2, 3, 4])

In [33]:
a.min()

np.int64(0)

In [35]:
a.sum()

np.int64(10)

In [37]:
a.mean()

np.float64(2.0)

In [38]:
a.std()

np.float64(1.4142135623730951)

In [39]:
n.min()

np.int64(0)